openapi: "3.0.0"

paths:
  /verify/solc-json:
    post:
      summary: Verify solc-json
      tags:
        - Stateless Verification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  format: address
                  description: Contract address
                  example: "0x07880D44b0f7b75464ad18fc2b980049c40A8bc3"
                chain:
                  type: string
                  format: supported-chainId
                  description: Chain to check
                  example: "1"
                files:
                  type: object
                  additionalProperties:
                    type: string
                  description: 'Files to upload {"path/filename": "content"}'
                  example:
                    value:
                      SolcJsonInput.json: "{...}"
                compilerVersion:
                  type: string
                  description: Compiler version
                  example: "0.8.4+commit.c7e474f2"
                contractName:
                  type: string
                  description: Name of the contract
                  example: "Storage"
                creatorTxHash:
                  type: string
                  description: Creator transaction hash
                  example: "0xb7efb33c736b1e8ea97e356467f99d99221343f077ce31a3e3ac1d2e0636df1d"
              required:
                - address
                - chain
                - compilerVersion
                - contractName
                - files
          multipart/form-data:
            schema:
              type: object
              properties:
                address:
                  type: string
                  format: address
                  description: Contract address
                chain:
                  type: string
                  format: supported-chainId
                  description: Chain to check
                files:
                  oneOf:
                    - type: string
                      format: binary
                    - type: array
                      items:
                        type: string
                        format: binary
                  description: File content for upload
                compilerVersion:
                  type: string
                  description: Compiler version
                contractName:
                  type: string
                  description: Name of the contract
                creatorTxHash:
                  type: string
                  description: Creator transaction hash
              required:
                - address
                - chain
                - compilerVersion
                - contractName
      responses:
        "200":
          description: The contract has been successfully checked or sourcified
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        address:
                          type: string
                        chainId:
                          type: string
                        status:
                          type: string
                        message:
                          type: string
                        libraryMap:
                          type: object
              examples:
                Perfect Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "perfect"
                        libraryMap:
                          lib1: "0x3f681646d4a755815f9cb19e1acc8565a0c2ac"
                          lib2: "0x4f681646d4a755815f9cb19e1acc8565a0c2ac"
                Partial Match:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "partial"
                        libraryMap:
                          lib1: "0x3f681646d4a755815f9cb19e1acc8565a0c2ac"
                          lib2: "0x4f681646d4a755815f9cb19e1acc8565a0c2ac"
                Not Deployed:
                  value:
                    result:
                      - address: "0x123f681646d4a755815f9cb19e1acc8565a0c2ac"
                        chainId: "1"
                        status: "null"
                        message: "Chain #1 does not have a contract deployed at 0x...."
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                One SolidityJSON at a time:
                  value:
                    error: "Only one Solidity JSON Input file at a time is allowed"
                Bad Formatted Json:
                  value:
                    error: "Unexpected token ' in JSON at position 107"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                File Not Found:
                  value:
                    error: "Couldn't extract files from the request. Please make sure you have added files"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Resource Missing:
                  value:
                    error: "Resource missing; unsuccessful fetching: contracts/SingleFile.sol"
                Deployed and recompiled mismatch:
                  value:
                    error: "The deployed and recompiled bytecode don't match."
