openapi: "3.0.0"

paths:
  /check-by-addresses:
    get:
      summary: Check by addresses (full match)
      description: Checks if contract with the desired chain and address is verified and in the repository.
      tags:
        - Repository
      parameters:
        - name: addresses
          in: query
          description: The addresses of the contracts.
          required: true
          schema:
            type: string
            format: comma-separated-addresses
        - name: chainIds
          in: query
          description: The IDs of the chains.
          required: true
          schema:
            type: string
            format: comma-separated-sourcify-chainIds
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                      example: "0xEb30853fc616Bbb8f1444451A3c202cbcd08Fb47"
                    status:
                      type: string
                      example: "perfect"
                    chainIds:
                      type: array
                      items:
                        type: string
                      example: ["43114", "137"]
