openapi: "3.0.0"

paths:
  /check-all-by-addresses:
    get:
      summary: Check if contracts are verified (perfect or partial match) by addresses
      description: Checks if contract with the desired chain and address is verified and in the repository. It will search for both perfect and partial matches.
      tags:
        - Repository
      parameters:
        - name: addresses
          in: query
          description: Comma seperated string of addresses to check for.
          required: true
          schema:
            type: string
            format: comma-separated-addresses
        - name: chainIds
          in: query
          description: Comma separated string of chain IDs.
          required: true
          schema:
            type: string
            format: comma-separated-sourcify-chainIds
      responses:
        "200":
          description: OK. Also returns `200` with status `false` when not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                    chainIds:
                      type: array
                      items:
                        type: object
                        properties:
                          chainId:
                            type: string
                          status:
                            type: string
              examples:
                multiple results:
                  value: 
                    - address: "0x6F1D75a53a8805DcA5347aE5F3eDE035CAE3CBC1"
                      chainIds: 
                        - chainId: "5"
                          status: "perfect"
                        - chainId: "10"
                          status: "partial"
                        - chainId: "11155111"
                          status: "perfect"
                    - address: "0x751D7C0Cf91a9b7704541b44E5fF7BeC3D2caA6F"
                      chainIds: 
                        - chainId: "5"
                          status: "partial"
                        - chainId: "10"
                          status: "perfect"
                    - address: "0x8D2548A5f641b00Cf0f5B693d4A72D8c0aE24d31"
                      chainIds:
                        - chainId: "5"
                          status: "perfect"
                    - address: "0x1f9cA631AE0C4890F99b38634C969b7E4f8719F0"
                      status: "false"
                single result:
                  value: 
                    - address: "0xEb30853fc616Bbb8f1444451A3c202cbcd08Fb47"
                      chainIds: 
                        - chainId: "43114"
                          status: "perfect"
                not found:
                  value: 
                    - address: "0x1f9cA631AE0C4890F99b38634C969b7E4f8719F0"
                      status: "false"
                    - address: "0x8D2548A5f641b00Cf0f5B693d4A72D8c0aE24d31"
                      statues: "false"