openapi: "3.0.0"

paths:
  /files/tree/any/{chain}/{address}:
    get:
      summary: Get file tree
      description: Returns repository URLs for every file in the source tree for the desired chain and address. Searches for full and partial matches.
      tags:
        - Repository
      parameters:
        - name: chain
          in: path
          required: true
          schema:
            type: string
            format: sourcify-chainId
        - name: address
          in: path
          required: true
          schema:
            type: string
            format: address
      responses:
        "200":
          description: Contract is available
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "full"
                  files:
                    type: array
                    items:
                      type: string
                    example:
                      [
                        "https://contractrepostaging.komputing.org/contracts/full_match/5/0x32a5d2240a60dcF7Af8EfAE6d886ec8BeD5f71bA/metadata.json",
                      ]
        "404":
          description: Contract is not available
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Files have not been found!"
