openapi: "3.0.0"

paths:
  /files/{chain}/{address}:
    get:
      summary: Get source files (full match)
      description: Returns all verified sources from the repository for the desired contract address and chain, including `metadata.json`. Searches only for full matches.
      tags:
        - Repository
      parameters:
        - name: chain
          in: path
          required: true
          schema:
            type: string
            format: sourcify-chainId
        - name: address
          in: path
          required: true
          schema:
            type: string
            format: address
      responses:
        "200":
          description: Contract is available in the repository
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "metadata.json"
                    path:
                      type: string
                      example: "/home/data/repository/contracts/full_match/3/0x0000A906D248Cc99FB8CB296C8Ad8C6Df05431c9/metadata.json"
                    content:
                      type: string
        "404":
          description: Contract is not available in the repository
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Files have not been found!"
