openapi: "3.0.0"

paths:
  /files/tree/{chain}/{address}:
    get:
      summary: Get file tree (full match)
      description: Returns repository URLs for every file in the source tree for the desired chain and address. Searches only for full matches.
      tags:
        - Repository
      parameters:
        - name: chain
          in: path
          required: true
          schema:
            type: string
            format: sourcify-chainId
        - name: address
          in: path
          required: true
          schema:
            type: string
            format: address
      responses:
        "200":
          description: Contract is available
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  [
                    "https://repo.sourcify.dev/contracts/full_match/5/0x1fE5d745beABA808AAdF52057Dd7AAA47b42cFD0/metadata.json",
                  ]
        "404":
          description: Contract is not available
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Files have not been found!"
