openapi: "3.0.0"

paths:
  /files/any/{chain}/{address}:
    get:
      summary: Get file tree
      description: Returns repository URLs for every file in the source tree for the desired chain and address. Searches for full and partial matches.
      tags:
        - Repository
      parameters:
        - name: chain
          in: path
          required: true
          schema:
            type: string
            format: sourcify-chainId
        - name: address
          in: path
          required: true
          schema:
            type: string
            format: address
      responses:
        "200":
          description: Contract is available
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "full"
                  files:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: "metadata.json"
                        path:
                          type: string
                          example: "/home/data/repository/contracts/full_match/3/0x0000A906D248Cc99FB8CB296C8Ad8C6Df05431c9/metadata.json"
                        content:
                          type: string
        "404":
          description: Contract is not available
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Files have not been found!"
