version: "3.7"

x-project-base: &project-base
  restart: always
  networks:
    - source-verify

networks:
  source-verify:

services:

  repository:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify/repository:${TAG}
    build:
      context: ./h5ai-nginx
    container_name: repository-${TAG}
    environment:
      # https://github.com/ethereum/sourcify/issues/1330
      # https://github.com/sourcifyeth/h5ai-nginx/pull/3
      - SOURCIFY_SERVER=http://host.docker.internal:5555
    volumes:
      - type: bind
        source: ./data
        target: /data
        read_only: true
    ports:
      # The `repository` app is exposed under port `:80` through `h5ai-nginx.conf.template`
      - "${REPOSITORY_PORT}:80"

  server:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify/server:${TAG}
    build:
      context: ./sourcify
      dockerfile: ./services/server/Dockerfile
    container_name: server-${TAG}
    environment:
      - NODE_ENV=development
    ports:
      # Value is set in `services/server/src/config/default.js`
      - "${SERVER_PORT}:5555"
    volumes:
      - type: bind
        source: ./servers.yaml
        target: /home/app/services/server/dist/servers.yaml
      - type: bind
        source: ./sourcify-chains.json
        target: /home/app/services/server/dist/sourcify-chains.json
      - type: bind
        source: ./data
        target: /tmp/sourcify/repository
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 30s
      timeout: 10s
      retries: 10

  ui:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify/ui:${TAG}
    build:
      context: ./ui
    container_name: ui-${TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - type: bind
        source: ./ui-config.json
        target: /usr/share/nginx/html/config.json
    ports:
      # The `ui` app is exposed under port `:80` through `nginx.conf`
      - "${UI_PORT}:80"
