version: "3.7"

x-project-base:
  &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

networks:
  source-verify:

services:
  monitor:
    <<: *project-base
    image: ethereum/source-verify:monitor-${TAG}
    container_name: monitor-${TAG}
    volumes:
      - type: bind
        source: $REPOSITORY_PATH_HOST
        target: $REPOSITORY_PATH
      - type: bind
        source: $SOLC_REPO_HOST
        target: $SOLC_REPO
        read_only: true
      - type: bind
        source: $SOLJSON_REPO_HOST
        target: $SOLJSON_REPO
        read_only: true
    ports:
    - "${MONITOR_EXTERNAL_PORT}:${MONITOR_PORT}"
