version: "3.7"

x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify
networks:
  source-verify:
# volumes:
#   db:
#   h5ai:
#     driver: local

services:
  repository:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify:repository-${TAG}
    container_name: repository-${TAG}
    volumes:
      - type: bind
        source: $REPOSITORY_PATH_HOST
        target: $REPOSITORY_PATH
        read_only: true
      - type: bind
        source: ./docker-config.json
        target: /redirects/config.json
    ports:
      - ${REPOSITORY_SERVER_EXTERNAL_PORT}:80
