version: "3.7"

x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

networks:
  source-verify:

services:
  s3sync:
    <<: *project-base
    image: ethereum/source-verify:s3-${TAG}
    container_name: s3-${TAG}
    volumes:
      - type: bind
        source: $REPOSITORY_PATH_HOST
        target: $REPOSITORY_PATH
