version: "3.7"
x-project-repository-mount: &project-repository-mount
  type: bind
  source: $REPOSITORY_PATH

x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

networks:
  source-verify:

services:
  server:
    <<: *project-base
#    image: gcr.io/hedera-registry/hedera-sourcify:server-${TAG}
    build:
      context: ../
      dockerfile: src/Dockerfile.server
    container_name: server-${TAG}
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    volumes:
      - <<: *project-repository-mount
        target: /home/data/repository
      - type: bind
        source: $SOLC_REPO_HOST
        target: $SOLC_REPO
      - type: bind
        source: $SOLJSON_REPO_HOST
        target: $SOLJSON_REPO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 10
