version: "3.7"

networks:
  source-verify:

x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

services:
  ui:
    <<: *project-base
    image: ghcr.io/hashgraph/hedera-sourcify:ui-${TAG}
    container_name: ui-${TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - type: bind
        source: ./docker-config.json
        target: /usr/share/nginx/html/config.json
    ports:
      - "${UI_EXTERNAL_PORT}:80"
