version: "3.7"

networks:
  source-verify:

x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

services:
  ui:
    <<: *project-base
    #    image: gcr.io/hedera-registry/hedera-sourcify:ui-${TAG}
    build:
      context: ../ui
      dockerfile: Dockerfile
      # Pass SERVER_URL and REPOSITORY_SERVER_URL to be injected build time.
      # Will be set in .env (see scripts/build_and_publish_docker_images.sh)
      args:
        - SERVER_URL=$SERVER_URL
        - REPOSITORY_SERVER_URL=$REPOSITORY_SERVER_URL
        - TAG=$TAG
    container_name: ui-${TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "${UI_EXTERNAL_PORT}:80"
