{
 "title": "Hedera Sourcify Server",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Verified Contracts per chainId",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({container=\"sourcify-server\"} |= `Verified contract` | json chainId | drop filename [$__auto])",
     "legendFormat": "Chain {{chainId}}"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"sourcify\", container=\"sourcify-server\"} | drop filename,namespace,node_name,pod,job,service_name [$__auto])"
    }
   ]
  },
  {
   "title": "Verification Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"sourcify\", container=\"sourcify-server\"} |= `Verifying contract` |drop filename,namespace,node_name,pod,job,service_name [$__auto])"
    }
   ]
  },
  {
   "title": "Errors and Warnings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"sourcify\", container=\"sourcify-server\"} | json level | level != `info` | level != `debug` | __error__=`` | drop filename [$__auto])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Compiler invocations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"sourcify\", container=\"sourcify-server\"} |= `Compiled contract` | drop filename,namespace,node_name,pod,job,service_name [$__auto])"
    }
   ]
  },
  {
   "title": "Local compilation fallbacks",
   "type": "timeseries",
   "description": "Lambda function failed due to an contract output bigger than 20 MB and therefore local compilation was invoked",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"sourcify\", container=\"sourcify-server\"} |= `Falling back to local compilation` | drop filename [$__auto])"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{namespace=\"sourcify\", container=\"sourcify-server\"} | json level | level = `error`"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "logs",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "{namespace=\"sourcify\", container=\"sourcify-server\"} | json level | level = `warn`"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{namespace=\"sourcify\", container=\"sourcify-server\"} |= ``"
    }
   ]
  }
 ]
}