{
 "title": "Sourcify Requests Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sourcify Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sourcify_http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sourcify - Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (rate(sourcify_http_request_duration_seconds_count[2m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Sourcify Request Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(sum by (le) (increase(sourcify_http_request_duration_seconds_bucket[$__rate_interval])), \"le\", \"Inf\", \"le\", \"\\\\+Inf\")",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Sourcify Request Duration Summary",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(sourcify_http_request_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sourcify Request Duration (Stacked All Buckets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (rate(sourcify_http_request_duration_seconds_bucket[3m]))\n",
     "legendFormat": "Requests > {{le}}s per second"
    }
   ]
  },
  {
   "title": "Sourcify Request Duration (Unstacked Buckets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"0.03\"}[3m])) - sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"0.003\"}[3m]))",
     "legendFormat": "0.003  <  t  <  0.03"
    },
    {
     "expr": "sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"0.1\"}[3m])) - sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"0.03\"}[3m]))",
     "legendFormat": "0.03  <  t  <  0.1"
    },
    {
     "expr": "sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"0.3\"}[3m])) - sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"0.1\"}[3m]))",
     "legendFormat": "0.1  <  t  < 0.3"
    },
    {
     "expr": "sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"1.5\"}[3m])) - sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"0.3\"}[3m]))",
     "legendFormat": "0.3  <  t  <  1.5"
    },
    {
     "expr": "sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"10\"}[3m])) - sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"1.5\"}[3m]))",
     "legendFormat": "1.5  <  t  <  10"
    },
    {
     "expr": "sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"+Inf\"}[3m])) - sum (rate(sourcify_http_request_duration_seconds_bucket{le=\"10\"}[3m]))",
     "legendFormat": "10  <  t"
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 0.3 seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (app) (increase(sourcify_http_request_duration_seconds_bucket{le=\"0.3\"}[1d])) / sum by (app) (increase(sourcify_http_request_duration_seconds_count[1d]))) * 100"
    }
   ]
  },
  {
   "title": "Container Restarts (last 3h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[3h]) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Request Duration (Stacked Buckets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app, le) (rate(sourcify_http_request_duration_seconds_count[3m]) - ignoring (le) group_right rate(sourcify_http_request_duration_seconds_bucket{le!=\"+Inf\"}[3m]))",
     "legendFormat": "Requests > {{le}}s per second"
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 0.3 seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(sum by (app) (rate(sourcify_http_request_duration_seconds_bucket{le=\"0.3\"}[2m])) / sum by (app) (rate(sourcify_http_request_duration_seconds_count[2m]))) * 100"
    }
   ]
  }
 ]
}