openapi: "3.0.0"

paths:
  /session/verify/create2:
    post:
      summary: Verify create2
      tags:
        - Session Verification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientToken:
                  type: string
                  description: Mandatory client token to call this api
                deployerAddress:
                  type: string
                  format: address
                  description: The deployer addresses
                salt:
                  oneOf:
                    - type: string
                    - type: number
                  description: Salt
                abiEncodedConstructorArguments:
                  type: string
                  description: ABI encoded constructor arguments
                create2Address:
                  type: string
                  format: address
                  description: The create2 addresses
                verificationId:
                  type: string
                  description: The verificationId of the checkedContract
              required:
                - deployerAddress
                - verificationId
                - create2Address
                - salt
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contracts:
                    type: array
                    items:
                      type: object
                      properties:
                        verificationId:
                          type: string
                          example: "0x8e2d0b6fef24d782a7c47e67ddfd2f5ca9cace335ce42bd10701ebba609e1244"
                        constructorArgumentsArray:
                          type: array
                          items:
                            type: object
                            properties:
                              internalType:
                                type: string
                              name:
                                type: string
                              type:
                                type: string
                        creationBytecode:
                          type: string
                          example: "0x608060405234801561001057600080fd5b5060405161020638038061020683398181016040528101906100329190610054565b80600081905550506100a7565b60008151905061004e81610090565b92915050565b60006020828403121561006a5761006961008b565b5b60006100788482850161003f565b91505092915050565b6000819050919050565b600080fd5b61009981610081565b81146100a457600080fd5b50565b610150806100b66000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100d9565b60405180910390f35b610073600480360381019061006e919061009d565b61007e565b005b60008054905090565b8060008190555050565b60008135905061009781610103565b92915050565b6000602082840312156100b3576100b26100fe565b5b60006100c184828501610088565b91505092915050565b6100d3816100f4565b82525050565b60006020820190506100ee60008301846100ca565b92915050565b6000819050919050565b600080fd5b61010c816100f4565b811461011757600080fd5b5056fea26469706673582212201d279c878911e1b98344e0d39ca1fe4c6aa7b9c649951e3abc365183e0e1695964736f6c63430008070033"
                        compiledPath:
                          type: string
                          example: "contracts/SingleFile.sol"
                        name:
                          type: string
                          example: "Storage"
                        address:
                          type: string
                          example: "0x4e3953cfaf4e3cc4e98d024aa1ec690733588e10"
                        files:
                          type: object
                          properties:
                            found:
                              type: array
                              items:
                                type: string
                                example: "contracts/SingleFile.sol"
                            missing:
                              type: object
                            invalid:
                              type: object
                        status:
                          type: string
                          example: "perfect"
                        storageTimestamp:
                          type: string
                          format: date-time
                          example: "2022-10-26T15:08:14.320Z"
                  unused:
                    type: array
                    items:
                      type: string
                  files:
                    type: array
                    items:
                      type: string
                      example: "metadata.json"
