{{- if and .Values.serverRepository.enabled .Values.serverRepository.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sourcify.serverRepository.serviceAccountName" . }}
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
  {{- with .Values.serverRepository.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
