version: '3.7'

services:

  nginx-service:
    container_name: nginx-container
    image: nginx
    restart: "unless-stopped"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../certificate:/etc/nginx/certificate
    ports:
      - "80:80"
      - "443:443"
