openapi: "3.0.0"

paths:
  /session/clear:
    post:
      summary: Clear session data
      tags:
        - Session Verification
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Session successfully cleared"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error in clearing session"
