openapi: "3.0.0"

paths:
  /session/data:
    get:
      summary: Get session data
      tags:
        - Session Verification
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contracts:
                    type: array
                    items:
                      type: object
                      properties:
                        verificationId:
                          type: string
                          example: "0x3f67e9f57515bb1e7195c7c5af1eff630091567c0bb65ba3dece57a56da766fe"
                        compiledPath:
                          type: string
                          example: "browser/1_Storage.sol"
                        name:
                          type: string
                          example: "Storage"
                        compilerVersion:
                          type: string
                          example: "0.6.6+commit.6c089d02"
                        files:
                          type: object
                          properties:
                            found:
                              type: array
                              items:
                                type: string
                            missing:
                              type: array
                              items:
                                type: string
                                example: "browser/1_Storage.sol"
                        status:
                          type: string
                          example: "error"
                  unused:
                    type: array
                    items:
                      type: string
