openapi: "3.0.0"

paths:
  /session/input-contract:
    post:
      summary: Import deployed contract trying to fetch metadata and files form IPFS
      tags:
        - Session Verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
                - chainId
              properties:
                address:
                  type: string
                  format: address
                chainId:
                  type: string
                  format: supported-chainId
          multipart/form-data:
            schema:
              type: object
              required:
                - address
                - chainId
              properties:
                address:
                  type: string
                  format: address
                chainId:
                  type: string
                  format: supported-chainId
      responses:
        "200":
          description: Response is sent when the upload is successful under different conditions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  contracts:
                    type: array
                    items:
                      type: object
                      properties:
                        compiledPath:
                          type: string
                          example: "browser/1_Storage.sol"
                        name:
                          type: string
                          example: "Storage"
                        compilerVersion:
                          type: string
                          example: "0.6.6+commit.6c089d02"
                        files:
                          type: object
                          properties:
                            found:
                              type: array
                              items:
                                type: string
                            missing:
                              type: array
                              items:
                                type: string
                        verificationId:
                          type: string
                          example: "0x3f67e9f57515bb1e7195c7c5af1eff630091567c0bb65ba3dece57a56da766fe"
                        status:
                          type: string
                          enum: ["perfect", "partial", "error"]
                  unused:
                    type: array
                    items:
                      type: string
        "413":
          description: Payload Too Large
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Too much session memory used. Delete some files or clear the session."
