{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sourcify.name" . }}-server
  labels:
    {{- include "sourcify.server.labels" . | nindent 4 }}
  {{- if .Values.server.annotations }}
  annotations:
  {{ toYaml .Values.server.annotations | indent 4 }}
  {{- end }}    
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
    {{- include "sourcify.server.labels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.server.podAnnotations }}
      annotations:
        {{- toYaml .Values.server.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "sourcify.server.serviceAccountName" . }}
      {{- if .Values.server.podSecurityContext}}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      {{- end }}  
      containers:
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.server,securityContext | nindent 12 }}
          image: "{{ .Values.image.server }}:{{ .Values.image.server.tag | default "server-latest" }}"
          imagePullPolicy: {{ .Values.image.server.pullPolicy }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: https
          readinessProbe:
            httpGet:
              path: /
              port: https
          {{- if .Values.server.resources }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.server.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.server.affinity }}
      affinity:
        {{- toYaml .Values.server.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.server.tolerations }}
      tolerations:
        {{- toYaml .Values.server.tolerations | nindent 8 }}
      {{- end }}
{{- end -}}