{{- if .Values.sourcify.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sourcify.fullname" . }}
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.repository.service.type }}
  ports:
    - port: {{ .Values.repository.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "sourcify.selectorLabels" . | nindent 4 }}
