apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Chart.Name "ui" }}
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
    {{- include "sourcify.ui.selectorLabels" . | nindent 4 }}
  {{- if .Values.ui.annotations }}
  annotations:
  {{ toYaml .Values.ui.annotations | indent 4 }}
  {{- end }}    
data: 
  config.json: |-
   {{- .Values.ui.config | toJson  | nindent 4 }}