apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sourcify.name" . }}
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
    {{- include "sourcify.serverRepository.selectorLabels" . | nindent 4 }}
  {{- if .Values.serverRepository.annotations }}
  annotations:
  {{ toYaml .Values.serverRepository.annotations | indent 4 }}
  {{- end }}
data:
  SERVER_URL: {{ .Values.serverRepository.config.SERVER_URL }}
  REPOSITORY_SERVER_URL: {{ .Values.serverRepository.config.REPOSITORY_SERVER_URL }}
  NODE_ENV: {{ .Values.serverRepository.config.NODE_ENV | default "development" }}
  SOURCIFY_SERVER: "http://{{ template "sourcify.name" . }}-server:5555"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Chart.Name "repository"  }}
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
    {{- include "sourcify.serverRepository.selectorLabels" . | nindent 4 }}
  {{- if .Values.serverRepository.annotations }}
  annotations:
  {{ toYaml .Values.serverRepository.annotations | indent 4 }}
  {{- end }}
data:
  servers.yaml: |-
  {{- .Values.serverRepository.config.servers | toYaml | nindent 4 }}
  sourcify-chains.json: |-
  {{- .Values.serverRepository.config.sourcifyChains | toJson | nindent 4 }}
  local.js: |
    module.exports = {
      repositoryV1: { path: "/data", },
      corsAllowedOrigins: [
          /^https?:\/\/(?:.+\.)?hedera-devops.com$/, // swirldslabs-devops
          /^https?:\/\/(?:.+\.)?hashscan.io$/, // hashscan
      ],
    };
