{{- if and .Values.serverRepository.enabled .Values.serverRepository.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "sourcify.name" . }}-serverRepository-pv
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
    {{- include "sourcify.serverRepository.selectorLabels" . | nindent 4 }}
  {{- if .Values.serverRepository.annotations }}
  annotations:
  {{ toYaml .Values.serverRepository.annotations | indent 4 }}
  {{- end }}
spec:
    capacity:
        storage: {{ .Values.serverRepository.persistence.size }}
    accessModes:
        - {{ .Values.serverRepository.persistence.accessMode }}
    storageClassName: {{ .Values.serverRepository.persistence.storageClassName }}
{{- end }}