apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Chart.Name "adapter" }}
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
    {{- include "sourcify.serverRepository.selectorLabels" . | nindent 4 }}
  {{- if .Values.serverRepository.annotations }}
  annotations:
  {{ toYaml .Values.serverRepository.annotations | indent 4 }}
  {{- end }}
tpye: kubernetes.io/tls
stringData:
  ca.crt: | 
{{ .Values.serverRepository.config.ca_cert| indent 4 }}
  ca.key: | 
{{ .Values.serverRepository.config.ca_key | indent 4 }}