{{- if .Values.serverRepository.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sourcify.fullname" . }}
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serverRepository.service.type }}
  ports:
    - port: {{ .Values.serverRepository.service.server.port }}
      targetPort: serverport
      protocol: TCP
      name: serverport
    - port: {{ .Values.serverRepository.service.repository.port }}
      targetPort: repositoryport
      protocol: TCP
      name: repositoryport
  selector:
    {{- include "sourcify.serverRepository.selectorLabels" . | nindent 4 }}
{{- end }}    
