{{- if .Values.serverRepository.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Chart.Name "server" }}
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serverRepository.service.type }}
  ports:
    - port: {{ .Values.serverRepository.service.server.port }}
      targetPort: serverport
      protocol: TCP
      name: serverport
  selector:
    {{- include "sourcify.serverRepository.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name:  {{ printf "%s-%s" .Chart.Name "repository" }}
  labels:
    {{- include "sourcify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serverRepository.service.type }}
  ports:
    - port: {{ .Values.serverRepository.service.repository.port }}
      targetPort: http
      protocol: TCP
      name: repositoryport
  selector:
    {{- include "sourcify.serverRepository.selectorLabels" . | nindent 4 }}
{{- end }}    
