openapi: "3.0.0"

paths:
  /session/input-solc-json:
    post:
      summary: Verify solc-json
      tags:
        - Session Verification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                files:
                  type: object
                  additionalProperties:
                    type: string
                  description: 'Files to upload {"path/filename": "content"}'
                compilerVersion:
                  type: string
                  description: Compiler version
              required:
                - compilerVersion
                - files
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  oneOf:
                    - type: string
                    - type: array
                      items:
                        type: string
                    - type: string
                      format: binary
                    - type: array
                      items:
                        type: string
                        format: binary
                compilerVersion:
                  type: string
                  description: Compiler version
              required:
                - compilerVersion
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contracts:
                    type: array
                    items:
                      type: object
                      properties:
                        verificationId:
                          type: string
                          example: "0x3f67e9f57515bb1e7195c7c5af1eff630091567c0bb65ba3dece57a56da766fe"
                        compiledPath:
                          type: string
                          example: "browser/1_Storage.sol"
                        name:
                          type: string
                          example: "Storage"
                        compilerVersion:
                          type: string
                          example: "0.6.6+commit.6c089d02"
                        address:
                          type: string
                          example: "0x656d0062eC89c940213E3F3170EA8b2add1c0143"
                        chainId:
                          type: string
                          example: "100"
                        files:
                          type: object
                          properties:
                            found:
                              type: array
                              items:
                                type: string
                                example: "browser/1_Storage.sol"
                            missing:
                              type: array
                              items:
                                type: string
                        status:
                          type: string
                          example: "perfect"
                        storageTimestamp:
                          type: string
                          format: date-time
                          example: "2021-01-12T15:41:56.502Z"
                  unused:
                    type: array
                    items:
                      type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "There are currently no pending contracts."
