{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels: {{ include "hedera-sourcify.labels" . | nindent 4 }}
  name: {{ include "hedera-sourcify.fullname" . }}-policy
  namespace: {{ include "hedera-sourcify.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: pgpool
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: hedera-sourcify
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: hedera-sourcify
{{- end -}}
